### ISSUE TITLE
It seems in the newest version of chrome, this does not work anymore.

### ISSUE THREAD

**Issue by john012343210** [AtomMaterialUI/material-dev-tools#219]
It seems in the newest version of chrome, this does not work anymore.

**Comment by mallowigi** [comment]
I am in Version 129.0.6668.90 (Official Build) (arm64), MacOS, and it works just fine (although 
it needs some adjustments that are long overdue)

![CleanShot 2024-10-06 at 08 53 54](https://github.com/user-attachments/assets/56acc6bb-874e-4eba-9582-7aad0fece016)
